// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: house.sql

package db

import (
	"context"
)

const getHouses = `-- name: GetHouses :many
SELECT id, owner, name, created_at FROM houses
WHERE owner = $1
ORDER BY name
LIMIT $2
OFFSET $3
`

type GetHousesParams struct {
	Owner  int64 `json:"owner"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetHouses(ctx context.Context, arg GetHousesParams) ([]House, error) {
	rows, err := q.db.Query(ctx, getHouses, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []House{}
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
