// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type House struct {
	ID        int64              `json:"id"`
	Owner     int64              `json:"owner"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HouseUser struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	HouseID   int64              `json:"house_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HousesUsersMap struct {
	UserID int64 `json:"user_id"`
}
